install.packages("devtools")
install.packages("huge")
install.packages("gtools")
library(devtools)
install_github("zdk123/SpiecEasi", ref="18cf96b6bb451d6eff4472857c55958e5ffbdf8b")
source("http://bioconductor.org/biocLite.R")
biocLite("phyloseq")
install.packages("Matrix")
install.packages("igraph")
install.packages("biclust")
install.packages("isa2")
